[package]
name = "dooly"
version = "0.1.0"
authors = ["Jaken Herman <jakenherman7@gmail.com>"]
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"